#!/usr/bin/env node

require('coffee-script/register');
var fragments = require('../src/fragments');
var hinoki = require('hinoki');
var umgebung = require('umgebung');

var source = hinoki.source([
  __dirname,
  fragments.source,
  umgebung
]);

source = hinoki.decorateSourceToAlsoLookupWithPrefix(source, 'fragments_');

module.exports = fragments(source);

if (require.main === module) {
  module.exports.runCommand();
}
