#!/usr/bin/env node

require('coffee-script/register');
var fragments = require('../src/fragments');

module.exports = fragments({
  init: (__dirname + '/init'),
  application: [(__dirname + '/application')],
  request: (__dirname + '/request'),
  middleware: (__dirname + '/middleware')
});

if (require.main === module) {
  module.exports.runCommand();
}
