#!/usr/bin/env node

var fragments = require('fragments');

module.exports = fragments({
  init: (__dirname + '/src/init'),
  application: (__dirname + '/src/application'),
  request: (__dirname + '/src/request'),
  middleware: (__dirname + '/src/middleware')
});

if (require.main === module) {
  module.exports.runCommand();
}
