#!/usr/bin/env node

var fragments = require('./src/fragments');
var hinoki = require('hinoki');

var source = hinoki.source([
  fragments.source,
  (__dirname + '/src/factories')
]);

module.exports = fragments(source);

if (require.main === module) {
  module.exports.runCommand();
}
