// Generated by CoffeeScript 1.9.1
var slice = [].slice,
  indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; };

module.exports.fragments_commandPrefix = function() {
  return 'command_';
};

module.exports.fragments_getCommandNamesFromLifetime = function(fragments_camelSnakeToHyphenColon, fragments_commandPrefix) {
  return function(lifetime) {
    return Object.keys(lifetime.factories).filter(function(x) {
      return x.indexOf(fragments_commandPrefix) === 0;
    }).map(function(x) {
      return x.slice(fragments_commandPrefix.length);
    }).map(fragments_camelSnakeToHyphenColon);
  };
};

module.exports.fragments_commandNameToFactoryPropertyName = function(fragments_commandPrefix, fragments_hyphenColonToCamelSnake) {
  return function(name) {
    return fragments_commandPrefix + fragments_hyphenColonToCamelSnake(name);
  };
};

module.exports.fragments_getCommandInLifetime = function(fragments_Promise, fragments_hinoki, fragments_commandNameToFactoryPropertyName) {
  return function(lifetime, commandName) {
    var commandFactory, commandKey;
    if (commandName == null) {
      commandName = 'help';
    }
    commandName = commandName.toLowerCase();
    commandKey = fragments_commandNameToFactoryPropertyName(commandName);
    commandFactory = lifetime.factories[commandKey];
    if (commandFactory == null) {
      return;
    }
    return function() {
      var args;
      args = 1 <= arguments.length ? slice.call(arguments, 0) : [];
      return fragments_hinoki.get(lifetime, commandKey).then(function(commandInstance) {
        return commandInstance.apply(null, args);
      });
    };
  };
};

module.exports.fragments_runCommand = function(fragments_getCommandInLifetime, fragments_applicationLifetime) {
  return function() {
    var args, command, commandName;
    commandName = arguments[0], args = 2 <= arguments.length ? slice.call(arguments, 1) : [];
    command = fragments_getCommandInLifetime(fragments_applicationLifetime, commandName);
    if (command != null) {
      return command.apply(null, args);
    } else {
      throw new Error("no such command: " + commandName);
    }
  };
};

module.exports.fragments_getCommandHelpLinesFromLifetime = function(fragments_getCommandNamesFromLifetime, fragments_commandNameToFactoryPropertyName, fragments_isjs, fragments_lodash) {
  return function() {
    var _, args, commandNames, lifetime, prefix;
    lifetime = arguments[0], args = 2 <= arguments.length ? slice.call(arguments, 1) : [];
    _ = fragments_lodash;
    commandNames = fragments_getCommandNamesFromLifetime(lifetime);
    if (args.length !== 0) {
      prefix = args.join(':');
      commandNames = _.filter(commandNames, function(name) {
        return fragments_isjs.startWith(name, prefix);
      });
    }
    commandNames = _.sortBy(commandNames);
    return commandNames.map(function(name) {
      var docstring, key, line;
      key = fragments_commandNameToFactoryPropertyName(name);
      line = name;
      docstring = lifetime.factories[key].$help;
      if (docstring != null) {
        line += ' ' + docstring;
      }
      return line;
    });
  };
};

module.exports.command_help = function(fragments_getCommandHelpLinesFromLifetime, fragments_applicationLifetime) {
  return function() {
    var args;
    args = 1 <= arguments.length ? slice.call(arguments, 0) : [];
    return fragments_getCommandHelpLinesFromLifetime.apply(null, [fragments_applicationLifetime].concat(slice.call(args))).forEach(function(line) {
      return console.log(line);
    });
  };
};

module.exports.command_help.$help = '[namespace-prefixes...] display available commands';

module.exports.command_serve = function(fragments_APPLICATION) {
  return function(serverCallbackName) {
    var factory;
    if (serverCallbackName == null) {
      serverCallbackName = 'server';
    }
    factory = function(Promise, http, onShutdown, shutdownBefore, console, port, baseUrl, serverCallback) {
      return new Promise(function(resolve, reject) {
        var server;
        server = http.createServer(serverCallback);
        server.on('listening', function() {
          onShutdown('server', function() {
            console.log('shutting down server by calling server.close()');
            return Promise.promisify(server.close, server)();
          });
          shutdownBefore('postgres', 'server');
          shutdownBefore('redis', 'server');
          console.log("go visit " + baseUrl);
          console.log('OK');
          return resolve();
        });
        server.on('error', reject);
        return server.listen(port);
      });
    };
    factory.$inject = ['fragments_Promise', 'fragments_http', 'fragments_onShutdown', 'fragments_shutdownBefore', 'fragments_console', 'fragments_config_port', 'fragments_config_baseUrl', serverCallbackName];
    return fragments_APPLICATION(factory);
  };
};

module.exports.command_serve.$help = "[server-callback-name (default: 'server')] - start a server with server-callback-name as callback";

module.exports.command_info = function(fragments_APPLICATION) {
  return fragments_APPLICATION(function(fragments_console) {
    return function() {
      var args;
      args = 1 <= arguments.length ? slice.call(arguments, 0) : [];
      fragments_console.log('TODO');
      return fragments_console.log('OK');
    };
  });
};

module.exports.command_pg_migrate = function(fragments_APPLICATION) {
  return fragments_APPLICATION(function(fragments_console, fragments_pgMigrate, fragments_shutdown, fragments_Promise) {
    return function() {
      var args, isDry, isVerbose;
      args = 1 <= arguments.length ? slice.call(arguments, 0) : [];
      isVerbose = indexOf.call(args, '--verbose') >= 0;
      isDry = indexOf.call(args, '--dry') >= 0;
      return fragments_pgMigrate(isVerbose, isDry)["catch"](function(err) {
        fragments_console.log('shutting down because of error:', err);
        return fragments_shutdown().then(function() {
          return fragments_Promise.reject(err);
        });
      }).then(function() {
        return fragments_shutdown();
      }).then(function() {
        return fragments_console.log('OK');
      });
    };
  });
};

module.exports.command_pg_migrate.$help = '[--verbose] [--dry] - migrate';

module.exports.command_migrations_create = function(fragments_APPLICATION) {
  return fragments_APPLICATION(function(fragments_console, fragments_fs, fragments_path, fragments_moment, fragments_config_migrationPath, fragments_Promise) {
    return function(name) {
      var filename, filepath, time;
      if (name == null) {
        fragments_console.log('Usage: ... migrations:create {migration-name}');
        return;
      }
      time = fragments_moment().format('YYYYMMDDHHmmss');
      filename = time + "-" + name + ".sql";
      filepath = fragments_path.join(fragments_config_migrationPath, filename);
      fragments_console.log(filepath);
      return fragments_fs.mkdirAsync(fragments_config_migrationPath)["catch"](function(err) {
        if (err.cause.code !== 'EEXIST') {
          return fragments_Promise.reject(err);
        }
      }).then(function() {
        return fragments_fs.writeFileAsync(filepath, '');
      }).then(function() {
        return fragments_console.log('OK');
      });
    };
  });
};

module.exports.command_migrations_create.$help = '{migration-name}';

module.exports.command_pg_create = function(fragments_APPLICATION) {
  return fragments_APPLICATION(function(fragments_console, fragments_pgCreate, fragments_shutdown, fragments_Promise) {
    return function() {
      return fragments_pgCreate()["catch"](function(err) {
        fragments_console.log('shutting down because of error:', err);
        return fragments_shutdown().then(function() {
          return fragments_Promise.reject(err);
        });
      }).then(function() {
        return fragments_shutdown();
      }).then(function() {
        return fragments_console.log('OK');
      });
    };
  });
};

module.exports.command_pg_drop = function(fragments_APPLICATION) {
  return fragments_APPLICATION(function(fragments_console, fragments_pgDrop, fragments_shutdown, fragments_Promise) {
    return function() {
      return fragments_pgDrop()["catch"](function(err) {
        fragments_console.log('shutting down because of error:', err);
        return fragments_shutdown().then(function() {
          return fragments_Promise.reject(err);
        });
      }).then(function() {
        return fragments_shutdown();
      }).then(function() {
        return fragments_console.log('OK');
      });
    };
  });
};

module.exports.command_pg_dropCreate = function(fragments_APPLICATION) {
  return fragments_APPLICATION(function(fragments_console, fragments_pgDropCreate, fragments_shutdown, fragments_Promise) {
    return function() {
      return fragments_pgDropCreate()["catch"](function(err) {
        fragments_console.log('shutting down because of error:', err);
        return fragments_shutdown().then(function() {
          return fragments_Promise.reject(err);
        });
      }).then(function() {
        return fragments_shutdown();
      }).then(function() {
        return fragments_console.log('OK');
      });
    };
  });
};

module.exports.command_pg_dropCreateMigrate = function(fragments_APPLICATION) {
  return fragments_APPLICATION(function(fragments_console, fragments_pgDropCreateMigrate, fragments_shutdown, fragments_Promise) {
    return function() {
      return fragments_pgDropCreateMigrate()["catch"](function(err) {
        fragments_console.log('shutting down because of error:', err);
        return fragments_shutdown().then(function() {
          return fragments_Promise.reject(err);
        });
      }).then(function() {
        return fragments_shutdown();
      }).then(function() {
        return fragments_console.log('OK');
      });
    };
  });
};
