// Generated by CoffeeScript 1.9.1
module.exports.fragments_encryptionAlgorithm = function() {
  return 'aes-256-cbc';
};

module.exports.fragments_encryptAesSha256 = function(fragments_crypto, fragments_encryptionAlgorithm) {
  return function(password, textToEncrypt) {
    var cipher, encrypted;
    cipher = fragments_crypto.createCipher(fragments_encryptionAlgorithm, password);
    encrypted = cipher.update(textToEncrypt, 'utf8', 'hex');
    encrypted += cipher.final('hex');
    return encrypted;
  };
};

module.exports.fragments_decryptAesSha256 = function(fragments_crypto, fragments_encryptionAlgorithm) {
  return function(password, textToDecrypt) {
    var decipher, decrypted;
    decipher = fragments_crypto.createDecipher(fragments_encryptionAlgorithm, password);
    decrypted = decipher.update(textToDecrypt, 'hex', 'utf8');
    decrypted += decipher.final('utf8');
    return decrypted;
  };
};
