// Generated by CoffeeScript 1.9.1
module.exports.fragments_process = function() {
  return process;
};

module.exports.fragments_console = function() {
  return console;
};

module.exports.fragments_env = function(fragments_process) {
  return fragments_process.env;
};

module.exports.fragments_argv = function(fragments_process) {
  return fragments_process.argv;
};
