// Generated by CoffeeScript 1.9.1
var slice = [].slice;

module.exports.fragments_kupToHtml = function(fragments_kup) {
  return function(f) {
    var k;
    k = new fragments_kup;
    f(k);
    return k.htmlOut;
  };
};

module.exports.fragments_reactKupToHtml = function(fragments_react, fragments_reactComponentToHtml) {
  return function(f) {
    return fragments_react.renderToStaticMarkup(fragments_react.kup(f));
  };
};

module.exports.fragments_reactToHtml = function(fragments_react) {
  return function() {
    var element, elementOrComponent, rest;
    elementOrComponent = arguments[0], rest = 2 <= arguments.length ? slice.call(arguments, 1) : [];
    element = fragments_react.isValidElement(elementOrComponent) ? elementOrComponent : fragments_react.createElement.apply(fragments_react, [elementOrComponent].concat(slice.call(rest)));
    return fragments_react.renderToStaticMarkup(element);
  };
};
