// Generated by CoffeeScript 1.9.2
module.exports.fragments_jwtRequestProperty = function() {
  return 'token';
};

module.exports.fragments_jwtMiddleware = function(fragments_expressJwt, fragments_jwtRequestProperty, fragments_config_jwtSigningSecret) {
  return fragments_expressJwt({
    secret: fragments_config_jwtSigningSecret,
    requestProperty: fragments_jwtRequestProperty
  });
};

module.exports.newJwt = function(fragments_jwt, fragments_encryptAesSha256, fragments_config_jwtEncryptionPassword, fragments_config_jwtSigningSecret) {
  return function(payload) {
    var encryptedPayload;
    encryptedPayload = fragments_encryptAesSha256(fragments_config_jwtEncryptionPassword, JSON.stringify(payload));
    return fragments_jwt.sign(encryptedPayload, fragments_config_jwtSigningSecret, {
      expirationInMinutes: 60
    });
  };
};

module.exports.fragments_decryptJwt = function(fragments_decryptAesSha256, fragments_config_jwtEncryptionPassword) {
  return function(encrypted) {
    return fragments_decryptAesSha256(fragments_config_jwtEncryptionPassword, encrypted);
  };
};
