// Generated by CoffeeScript 1.9.1
module.exports.fragments_APPLICATION = function(fragments_applicationLifetime, fragments_hinoki) {
  return function(factory) {
    return fragments_hinoki.get(fragments_applicationLifetime, fragments_hinoki.getAndCacheNamesToInject(factory)).spread(factory);
  };
};
