// Generated by CoffeeScript 1.9.2
module.exports.fragments_RedisSessionStore = function(fragments_expressSession, fragments_connectRedis) {
  return fragments_connectRedis(fragments_expressSession);
};

module.exports.fragments_redisSessionStore = function(fragments_RedisSessionStore, fragments_redisClient, fragments_config_redisSessionStorePrefix) {
  return new fragments_RedisSessionStore({
    client: fragments_redisClient,
    prefix: fragments_config_redisSessionStorePrefix
  });
};

module.exports.fragments_sessionMiddleware = function(fragments_expressSession, fragments_config_sessionSecret, fragments_redisSessionStore, fragments_uuid) {
  return fragments_expressSession({
    secret: fragments_config_sessionSecret,
    store: fragments_redisSessionStore,
    genid: function() {
      return fragments_uuid.v4();
    },
    saveUninitialized: true,
    resave: false,
    cookie: {
      httpOnly: true
    }
  });
};
