// Generated by CoffeeScript 1.9.2
module.exports.fragments_camelToSnake = function() {
  return function(string) {
    return string.replace(/([a-z][A-Z])/g, function(m) {
      return m[0] + '_' + m[1].toLowerCase();
    });
  };
};

module.exports.fragments_snakeToCamel = function() {
  return function(string) {
    return string.replace(/_([a-z])/g, function(m) {
      return m[1].toUpperCase();
    });
  };
};

module.exports.fragments_camelToHyphen = function() {
  return function(string) {
    return string.replace(/([a-z][A-Z])/g, function(m) {
      return m[0] + '-' + m[1].toLowerCase();
    });
  };
};

module.exports.fragments_hyphenToCamel = function() {
  return function(string) {
    return string.replace(/-([a-z])/g, function(m) {
      return m[1].toUpperCase();
    });
  };
};

module.exports.fragments_colonToSnake = function() {
  return function(string) {
    return string.replace(/:/g, '_');
  };
};

module.exports.fragments_snakeToColon = function() {
  return function(string) {
    return string.replace(/_/g, ':');
  };
};

module.exports.fragments_hyphenColonToCamelSnake = function(fragments_hyphenToCamel, fragments_colonToSnake) {
  return function(string) {
    return fragments_hyphenToCamel(fragments_colonToSnake(string));
  };
};

module.exports.fragments_camelSnakeToHyphenColon = function(fragments_camelToHyphen, fragments_snakeToColon) {
  return function(string) {
    return fragments_camelToHyphen(fragments_snakeToColon(string));
  };
};
