// Generated by CoffeeScript 1.9.3
module.exports.fragments_autoHeaders = function() {
  var secondsInADay, secondsInAYear;
  secondsInADay = 24 * 60 * 60;
  secondsInAYear = 365 * secondsInADay;
  return {
    'x-frame-options': 'sameorigin',
    'x-xss-protection': '1; mode=block',
    'x-content-type-options': 'nosniff',
    'strict-transport-security': "max-age=" + secondsInADay,
    'vary': 'accept-encoding'
  };
};

module.exports.fragments_autoHeadersMiddleware = function(fragments_MIDDLEWARE) {
  return fragments_MIDDLEWARE(function(fragments_setHeaders, fragments_autoHeaders, fragments_next) {
    fragments_setHeaders(fragments_autoHeaders);
    return fragments_next();
  });
};
