// Generated by CoffeeScript 1.9.3
var slice = [].slice;

module.exports.fragments_endUnauthorizedRequiresBasicAuth = function(fragments_setHeaderWWWAuthenticate, fragments_endUnauthorized) {
  return function() {
    var args;
    args = 1 <= arguments.length ? slice.call(arguments, 0) : [];
    fragments_setHeaderWWWAuthenticate('basic realm="secure area"');
    return fragments_endUnauthorized.apply(null, args);
  };
};

module.exports.fragments_basicAuthCredentials = function(fragments_req, fragments_basicAuth) {
  return fragments_basicAuth(fragments_req) || null;
};
