// Generated by CoffeeScript 1.9.2
module.exports.fragments_config_port = function(envIntPort) {
  return envIntPort;
};

module.exports.fragments_config_baseUrl = function(envStringBaseUrl) {
  return envStringBaseUrl;
};

module.exports.fragments_config_staticPath = function(envStringStaticPath) {
  return envStringStaticPath;
};

module.exports.fragments_config_jwtSigningSecret = function(envStringJwtSigningSecret) {
  return envStringJwtSigningSecret;
};

module.exports.fragments_config_jwtEncryptionPassword = function(envStringJwtEncryptionPassword) {
  return envStringJwtEncryptionPassword;
};

module.exports.fragments_config_redisUrl = function(envStringRedisUrl) {
  return envStringRedisUrl;
};

module.exports.fragments_config_redisDatabase = function(envIntRedisDatabase) {
  return envIntRedisDatabase;
};

module.exports.fragments_config_redisSessionStorePrefix = function(envStringRedisSessionStorePrefix) {
  return envStringRedisSessionStorePrefix;
};

module.exports.fragments_config_sessionSecret = function(envStringSessionSecret) {
  return envStringSessionSecret;
};

module.exports.fragments_config_bcryptCost = function(envIntBcryptCost) {
  return envIntBcryptCost;
};
