// Generated by CoffeeScript 1.10.0
module.exports.fragments_process = function() {
  return process;
};

module.exports.fragments_console = function() {
  return console;
};

module.exports.fragments_argv = function(fragments_process) {
  return fragments_process.argv;
};
