// Generated by CoffeeScript 1.9.2
module.exports.fragments_APPLICATION = function(fragments_applicationLifetime, fragments_hinoki, fragments_source) {
  return function(factory) {
    return fragments_hinoki(fragments_source, fragments_applicationLifetime, fragments_hinoki.getNamesToInject(factory)).spread(factory);
  };
};
