// Generated by CoffeeScript 1.9.3
module.exports.fragments_APPLICATION = function(fragments_applicationLifetime, fragments_hinoki, fragments_source) {
  return function(factory) {
    return fragments_hinoki(fragments_source, fragments_applicationLifetime, factory);
  };
};
