// Generated by CoffeeScript 1.9.3
module.exports.fragments_MIDDLEWARE = function(fragments_hinoki, fragments_source, fragments_applicationLifetime) {
  return function(factoryOrName) {
    return function(req, res, next, params) {
      if (req.hinokiRequestLifetime == null) {
        req.hinokiRequestLifetime = {
          fragments_req: req,
          fragments_res: res
        };
      }
      return fragments_hinoki(fragments_source, [
        fragments_applicationLifetime, req.hinokiRequestLifetime, {
          fragments_next: next,
          fragments_params: params
        }
      ], factoryOrName)["catch"](function(err) {
        console.log('ERROR');
        console.log(err);
        console.log(err.stack);
        res.statusCode = 500;
        return res.end('Server Error');
      });
    };
  };
};

['get', 'post', 'put', 'delete', 'patch', 'any'].forEach(function(method) {
  return module.exports["fragments_" + (method.toUpperCase())] = function(fragments_passage, fragments_MIDDLEWARE) {
    return function(urlPattern, factoryOrName) {
      return fragments_passage[method](urlPattern, fragments_MIDDLEWARE(factoryOrName));
    };
  };
});
