// Generated by CoffeeScript 1.10.0
module.exports.fragments_redisClient = function(fragments_Promise, fragments_url, fragments_redis, fragments_console, fragments_config_redisUrl, fragments_config_redisDatabase, fragments_config_redisPrefix, fragments_onShutdown) {
  var options, parsedRedisURL, redisClient, redisHost, redisPassword, redisPort;
  parsedRedisURL = fragments_url.parse(fragments_config_redisUrl);
  redisPort = parsedRedisURL.port;
  redisHost = parsedRedisURL.hostname;
  if (parsedRedisURL.auth != null) {
    redisPassword = parsedRedisURL.auth.split(':')[1];
  }
  options = {
    prefix: fragments_config_redisPrefix
  };
  redisClient = fragments_redis.createClient(redisPort, redisHost, options);
  if (redisPassword != null) {
    redisClient.auth(redisPassword);
  }
  if (fragments_config_redisDatabase != null) {
    redisClient.select(fragments_config_redisDatabase);
  }
  fragments_onShutdown('redis', function() {
    fragments_console.log('shutting down redis by calling redisClient.end()');
    return new fragments_Promise(function(resolve, reject) {
      redisClient.on('end', function() {
        fragments_console.log('redis client has ended');
        return resolve();
      });
      return redisClient.quit();
    });
  });
  return redisClient;
};
