// Generated by CoffeeScript 1.9.3
module.exports.fragments_shutdownState = function(fragments_zuvor) {
  return {
    isShutdown: false,
    callbacks: {},
    order: new fragments_zuvor.Graph()
  };
};

module.exports.fragments_isShutdown = function(fragments_shutdownState) {
  return function() {
    return fragments_shutdownState.isShutdown;
  };
};

module.exports.fragments_onShutdown = function(fragments_shutdownState) {
  return function(key, cb) {
    if ('function' !== typeof cb) {
      throw new Error('cb argument must be a function');
    }
    if (fragments_shutdownState.callbacks[key] != null) {
      throw new Error("shutdown callback already registered for key `" + key + "`");
    }
    return fragments_shutdownState.callbacks[key] = cb;
  };
};

module.exports.fragments_shutdownBefore = function(fragments_shutdownState) {
  return function(before, after) {
    return fragments_shutdownState.order.add(before, after);
  };
};

module.exports.fragments_shutdown = function(fragments_Promise, fragments_shutdownState, fragments_isShutdown, fragments_console, fragments_zuvor) {
  return function() {
    if (fragments_isShutdown()) {
      throw new Error('shutdown can only be called once per application lifetime');
    }
    fragments_shutdownState.isShutdown = true;
    fragments_console.log('shutting down');
    fragments_console.log('shutdown callbacks:');
    fragments_console.log(Object.keys(fragments_shutdownState.callbacks));
    fragments_console.log('shutdown order:');
    fragments_console.log(fragments_shutdownState.order.edges());
    return fragments_zuvor.run({
      ids: Object.keys(fragments_shutdownState.callbacks),
      graph: fragments_shutdownState.order,
      callback: function(id) {
        var callback;
        callback = fragments_shutdownState.callbacks[id];
        if (callback != null) {
          fragments_console.log("calling shutdown callback `" + id + "`");
          return callback();
        } else {
          fragments_console.log("no shutdown callback for `" + id + "` - ignoring");
          return fragments_Promise.resolve();
        }
      }
    }).then(function() {
      return fragments_console.log('shutdown complete');
    });
  };
};
