// Generated by CoffeeScript 1.9.3
var _, hinoki;

hinoki = require('hinoki');

_ = require('lodash');

module.exports = function(arg) {
  var result, source;
  source = arg != null ? hinoki.source(arg) : module.exports.source;
  result = function(factory) {
    var applicationLifetime;
    applicationLifetime = {};
    applicationLifetime.fragments_applicationLifetime = applicationLifetime;
    applicationLifetime.fragments_source = source;
    return hinoki(source, applicationLifetime, function(fragments_APPLICATION) {
      return fragments_APPLICATION(factory);
    });
  };
  result.runCommand = function(args) {
    var applicationLifetime;
    if (args == null) {
      args = process.argv.slice(2);
    }
    applicationLifetime = {};
    applicationLifetime.fragments_applicationLifetime = applicationLifetime;
    applicationLifetime.fragments_source = source;
    return hinoki(source, applicationLifetime, function(fragments_runCommand) {
      return fragments_runCommand.apply(null, args);
    });
  };
  return result;
};

module.exports.source = hinoki.source(__dirname + '/factories');
