// Generated by CoffeeScript 1.9.1
var slice = [].slice;

module.exports.fragments_endHTML = function(fragments_setHeaderContentTypeHTML, fragments_end) {
  return function() {
    var args;
    args = 1 <= arguments.length ? slice.call(arguments, 0) : [];
    fragments_setHeaderContentTypeHTML();
    return fragments_end.apply(null, args);
  };
};

module.exports.fragments_endReact = function(fragments_reactToHtml, fragments_endHTML) {
  return function() {
    var args;
    args = 1 <= arguments.length ? slice.call(arguments, 0) : [];
    return fragments_endHTML(fragments_reactToHtml.apply(null, args));
  };
};
