// Generated by CoffeeScript 1.9.2
module.exports.fragments_token = function(fragments_expressJwt, fragments_req, fragments_res, fragments_jwtMiddleware, fragments_jwtRequestProperty, fragments_decryptJwt, fragments_Promise) {
  if (fragments_req[fragments_jwtRequestProperty] != null) {
    return JSON.parse(fragments_decryptJwt(fragments_req[fragments_jwtRequestProperty]));
  }
  return new fragments_Promise(function(resolve, reject) {
    return fragments_jwtMiddleware(fragments_req, fragments_res, function() {
      if (typeof err !== "undefined" && err !== null) {
        return reject(err);
      }
      if (fragments_req[fragments_jwtRequestProperty] != null) {
        return resolve(JSON.parse(fragments_decryptJwt(fragments_req[fragments_jwtRequestProperty])));
      } else {
        return resolve(null);
      }
    });
  });
};
