// Generated by CoffeeScript 1.9.1
var slice = [].slice;

module.exports.fragments_write = function(fragments_res) {
  return function() {
    var args;
    args = 1 <= arguments.length ? slice.call(arguments, 0) : [];
    return fragments_res.write.apply(fragments_res, args);
  };
};

module.exports.fragments_end = function(fragments_res) {
  return function() {
    var args;
    args = 1 <= arguments.length ? slice.call(arguments, 0) : [];
    return fragments_res.end.apply(fragments_res, args);
  };
};

module.exports.fragments_endJSON = function(fragments_endNotFound, fragments_setHeaderContentTypeJSON, fragments_end) {
  return function(object) {
    fragments_setHeaderContentTypeJSON();
    return fragments_end(JSON.stringify(object));
  };
};

module.exports.fragments_endXML = function(fragments_endNotFound, fragments_setHeaderContentTypeXML, fragments_end) {
  return function() {
    var args;
    args = 1 <= arguments.length ? slice.call(arguments, 0) : [];
    fragments_setHeaderContentTypeXML();
    return fragments_end.apply(null, args);
  };
};

module.exports.fragments_endText = function(fragments_setHeaderContentTypeText, fragments_end) {
  return function() {
    var args;
    args = 1 <= arguments.length ? slice.call(arguments, 0) : [];
    fragments_setHeaderContentTypeText();
    return fragments_end.apply(null, args);
  };
};
