// Generated by CoffeeScript 1.9.2
module.exports.fragments_session = function(fragments_sessionMiddleware, fragments_req, fragments_res, fragments_Promise) {
  if (fragments_req.session != null) {
    return fragments_req.session;
  }
  return new fragments_Promise(function(resolve, reject) {
    return fragments_sessionMiddleware(fragments_req, fragments_res, function(err) {
      if (err != null) {
        return reject(err);
      }
      return resolve(fragments_req.session);
    });
  });
};

module.exports.fragments_sessionID = function(fragments_req, fragments_session) {
  return fragments_req.sessionID;
};
